import { randomUUID } from 'node:crypto';
import admin from 'firebase-admin';
const PROJECT_ID='nichegamesfinder',DATABASE_URL='https://nichegamesfinder-default-rtdb.firebaseio.com';
const queries=[...'abcdefghijklmnopqrstuvwxyz',...'0123456789','obby','simulator','tycoon','horror','survival','rpg','roleplay','fighting','shooter','adventure','sports','racing','anime','tower defense','sandbox','social','hangout','strategy','puzzle','story','escape','battle','city','school','life','meme','rng','clicker','incremental','building','zombie','parkour','driving','football','basketball','soccer','chill','open world','pvp','pve','scary','fps','minigames','vehicle','dress up','music','showcase'];
const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Missing FIREBASE_SERVICE_ACCOUNT_JSON');const sa=JSON.parse(raw);admin.initializeApp({credential:admin.credential.cert(sa),databaseURL:DATABASE_URL,projectId:PROJECT_ID});const db=admin.database(),root=db.ref('nichegames');
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
async function fetchJson(url){let last;for(let a=0;a<4;a++){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Nichegames/8.3-discovery'},signal:c.signal});clearTimeout(t);if(r.status===429||r.status>=500){await sleep(400*(a+1));continue;}if(!r.ok)throw new Error(`${r.status}`);return await r.json();}catch(e){last=e;await sleep(300*(a+1));}}throw last;}
async function pool(items,n,fn){let i=0;await Promise.all(Array.from({length:Math.min(n,items.length||1)},async()=>{while(true){const x=i++;if(x>=items.length)return;await fn(items[x],x);}}));}
function extract(payload,universes,places){const walk=(v)=>{if(!v||typeof v!=='object')return;if(Array.isArray(v))return v.forEach(walk);const u=Number(v.universeId??v.universeID??v.universe_id);if(Number.isSafeInteger(u)&&u>0)universes.add(u);const p=Number(v.placeId??v.placeID??v.place_id??v.rootPlaceId??v.rootPlaceID??v.root_place_id);if(Number.isSafeInteger(p)&&p>0)places.add(p);Object.values(v).forEach(walk);};walk(payload);}
async function updateChunked(path,ids,size=1000){const arr=[...ids];for(let i=0;i<arr.length;i+=size){const patch={};for(const id of arr.slice(i,i+size))patch[String(id)]=true;await root.child(path).update(patch);}}
const universes=new Set(),places=new Set();const started=new Date().toISOString();await root.child('jobs/discovery').set({status:'processing',startedAt:started,queries:queries.length});
console.log(`[Nichegames discovery] Parallel search across ${queries.length} query families.`);
await pool(queries,8,async(q,qi)=>{const sessionId=randomUUID();let token='';for(let page=0;page<3;page++){try{const p=new URLSearchParams({searchQuery:q,sessionId,pageType:'all'});if(token)p.set('pageToken',token);const data=await fetchJson(`https://apis.roblox.com/search-api/omni-search?${p}`);extract(data,universes,places);token=String(data?.nextPageToken||'');if(!token)break;}catch{break;}}if((qi+1)%10===0)console.log(`[Nichegames discovery] ${qi+1}/${queries.length} queries · ${universes.size} universes · ${places.size} places`);});
await pool(['computer','phone','tablet'],3,async(device)=>{const sessionId=randomUUID();try{const sorts=await fetchJson(`https://apis.roblox.com/explore-api/v1/get-sorts?${new URLSearchParams({sessionId,device,country:'all'})}`);extract(sorts,universes,places);const ids=[];const walk=(v)=>{if(!v||typeof v!=='object')return;if(Array.isArray(v))return v.forEach(walk);for(const[k,x]of Object.entries(v)){if(/^sortId$/i.test(k)&&(typeof x==='string'||typeof x==='number'))ids.push(String(x));else if(x&&typeof x==='object')walk(x);}};walk(sorts);await pool([...new Set(ids)],8,async(sortId)=>{try{const d=await fetchJson(`https://apis.roblox.com/explore-api/v1/get-sort-content?${new URLSearchParams({sessionId,sortId,device,country:'all'})}`);extract(d,universes,places);}catch{}});}catch{}});
await Promise.all([updateChunked('knownIds',universes),updateChunked('pendingPlaceIds',places)]);const done=new Date().toISOString();await root.child('meta').update({lastParallelDiscoveryAt:done,lastDiscoveryUniverses:universes.size,lastDiscoveryPlaces:places.size,workerArchitecture:'parallel-v8.3'});await root.child('jobs/discovery').update({status:'complete',completedAt:done,universes:universes.size,places:places.size});console.log(`[Nichegames discovery] Complete · ${universes.size} universe IDs · ${places.size} place IDs.`);
try{db.goOffline();await admin.app().delete();}catch{}
